TimeTracker/config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                   Controller#Action
#    companies GET    /companies(.:format)          companies#index
#              POST   /companies(.:format)          companies#create
#  new_company GET    /companies/new(.:format)      companies#new
# edit_company GET    /companies/:id/edit(.:format) companies#edit
#      company GET    /companies/:id(.:format)      companies#show
#              PATCH  /companies/:id(.:format)      companies#update
#              PUT    /companies/:id(.:format)      companies#update
#              DELETE /companies/:id(.:format)      companies#destroy
#     projects GET    /projects(.:format)           projects#index
#              POST   /projects(.:format)           projects#create
#  new_project GET    /projects/new(.:format)       projects#new
# edit_project GET    /projects/:id/edit(.:format)  projects#edit
#      project GET    /projects/:id(.:format)       projects#show
#              PATCH  /projects/:id(.:format)       projects#update
#              PUT    /projects/:id(.:format)       projects#update
#              DELETE /projects/:id(.:format)       projects#destroy
#        works GET    /works(.:format)              works#index
#              POST   /works(.:format)              works#create
#     new_work GET    /works/new(.:format)          works#new
#    edit_work GET    /works/:id/edit(.:format)     works#edit
#         work GET    /works/:id(.:format)          works#show
#              PATCH  /works/:id(.:format)          works#update
#              PUT    /works/:id(.:format)          works#update
#              DELETE /works/:id(.:format)          works#destroy
#

Rails.application.routes.draw do
  devise_for :users
  root 'companies#index'
  get 'recentworks/:days', to: 'works#index'
  get 'venture/:slug', to: 'projects#show'
  resources :companies
  resources :projects
  resources :works
end

TimeTracker/app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id           :integer          not null, primary key
#  name         :string
#  default_rate :decimal(, )
#  company_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Project < ApplicationRecord
  extend CsvModule

  belongs_to :company
  has_many :works
  has_many :users, through: :works

  validates :slug, length: { minimum: 3 }
  validates :slug, uniqueness: true
  validates :name, length: { minimum: 3 }
  validates :company, presence: true
  validates :default_rate, numericality: { greater_than: 10,
  less_than: 10000}

  before_validation :generate_slug

  def hours_worked
    total = works.map(&:hours).reduce(:+)
    total ||= 0
    total
  end

  def total_cost
    hours_worked * default_rate
  end

  def to_s
    "#{name} #{company}"
  end

  private

  def generate_slug
    self.slug = name.downcase.tr(' ', '-')
  end
end

TimeTracker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update]
  before_action :authenticate_user!, except: :index

  def index
    @projects = Project.all.order(created_at: :desc)
    respond_to do |format|
      format.html # defaults to show.html.erb
      format.json { render json: @projects }
      format.csv { send_data @projects.to_csv }
    end
  end

  def show
    respond_to do |format|
      format.html # defaults to show.html.erb
      format.json { render json: @project }
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project successfully updated'
      redirect_to @project
    else
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project successfully created'
      redirect_to @project
    else
      render :new
    end
  end

  private

  def project_params
    params[:project].permit(:company_id, :name, :default_rate)
  end

  def set_project
    slug = params[:slug]
    if slug
      @project = Project.find_by(slug: slug)
    else
      @project = Project.find(params[:id])
    end
  end
end

TimeTracker/app/helpers/projects_helper.rb
module ProjectsHelper
end

TimeTracker/app/views/projects/_form.html.erb
<%= form_with model: project, local: true, class: 'pure-form pure-form-stacked' do |f| %>
  <fieldset>
    <% if project.persisted? %>
      <legend>Update Project</legend>
    <% else %>
      <legend>Create Project</legend>
    <% end %>
    <div class="pure-control-group">
      <%= f.label :company_id, 'Company' %>
      <!-- Map project_id to id from Project display name of Project -->
      <%= f.collection_select :company_id, Company.all, :id, :name, id: :project_company_id, prompt: true, class: 'pure-input-1-2' %>
    </div>
    <div class="pure-control-group">
      <%= f.label :name %>
      <%= f.text_field :name, id: :project_name, class: 'pure-input-1-2', placeholder: 'Project Name' %>
    </div>
    <div class="pure-control-group">
      <%= f.label :default_rate, 'Rate' %>
      <%= f.number_field :default_rate, id: :project_default_rate, step: :any,  class: 'pure-input-1-2' %>
    </div>
    <div class="pure-control-group">
      <% if project.persisted? %>
        <%= f.submit 'Update Project', class: 'pure-button pure-button-primary' %>
      <% else %>
        <%= f.submit 'Create Project', class: 'pure-button pure-button-primary' %>
      <% end %>
    </div>
  </fieldset>
<% end %>

TimeTracker/app/views/projects/_project.html.erb
<tr>
  <td>
    <span><%= link_to "#{project.name}", project_path(project) %></span>
  </td>
  <td>
    <span><%= link_to "#{project.company.name}", company_path(project.company) %></span>
  </td>
  <td>
    <span><%= pluralize(project.hours_worked, 'hour') %></span>
  </td>
</tr>

TimeTracker/app/views/projects/_sidebar.html.erb
<h3>Aside</h3>
<ul>
  <li>
    <%= link_to 'All Projects', projects_path %>
  </li>
  <li>
    <%= link_to 'New Project', new_project_path %>
  </li>
  <% if local_assigns.has_key? :project %>
    <li>
      <%= link_to 'Edit Project', edit_project_path(project) %>
    </li>
  <% end %>
</ul>

TimeTracker/app/views/projects/edit.html.erb
<%= render 'shared/form-errors', model: @project %>
<%= render 'form', project: @project %>

<!-- provide content from application.html.erb -->
<% content_for :aside do %>
  <% render 'sidebar' %>
<% end %>

TimeTracker/app/views/projects/index.html.erb
<div>
  <table>
    <thead>
      <tr>
        <td>
          Name
        </td>
        <td>
          Company
        </td>
        <td>
          Hours Worked
        </td>
      </tr>
    </thead>
    <tbody>
      <%= render @projects %>
    </tbody>
  </table>
  <!-- provide content from application.html.erb -->
  <% content_for :aside do %>
    <% render 'sidebar' %><% end %>
  </div>

TimeTracker/app/views/projects/new.html.erb
<%= render 'shared/form-errors', model: @project %>
<%= render 'form', project: @project %>

<!-- provide content from application.html.erb -->
<% content_for :aside do %>
  <% render 'sidebar' %>
<% end %>

TimeTracker/app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p>
  Codename
  <%= @project.slug %>
</p>
<p>
  Total Time Spent
  <%= pluralize(@project.hours_worked, 'hour') %>
</p>

<p >
  Project Cost:
  <span class="price">
    <%= number_to_currency(@project.total_cost, precision: 2) %>
  </span>
</p>

<% if @project.works.count > 0 %>
  <div>
    <table>
      <thead>
        <%= render 'works/work-table-header' %>
      </thead>
      <tbody>
        <%= render partial: 'works/work', collection: @project.works %>
      </tbody>
    </table>

  </div>
<% else %>
  <p>
    No work has been completed for this project.
  </p>
<% end %>

<!-- provide content from application.html.erb -->
<% content_for :aside do %>
  <% render 'sidebar', project: @project %>
<% end %>