Resume/config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /login(.:format)               devise/sessions#new
#             user_session POST   /login(.:format)               devise/sessions#create
#     destroy_user_session DELETE /logout(.:format)              devise/sessions#destroy
#        new_user_password GET    /password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /password/edit(.:format)       devise/passwords#edit
#            user_password PATCH  /password(.:format)            devise/passwords#update
#                          PUT    /password(.:format)            devise/passwords#update
#                          POST   /password(.:format)            devise/passwords#create
# cancel_user_registration GET    /cancel(.:format)              devise/registrations#cancel
#    new_user_registration GET    /register(.:format)            devise/registrations#new
#   edit_user_registration GET    /edit(.:format)                devise/registrations#edit
#        user_registration PATCH  /                              devise/registrations#update
#                          PUT    /                              devise/registrations#update
#                          DELETE /                              devise/registrations#destroy
#                          POST   /                              devise/registrations#create
#               portfolios GET    /portfolios(.:format)          portfolios#index
#                          POST   /portfolios(.:format)          portfolios#create
#            new_portfolio GET    /portfolios/new(.:format)      portfolios#new
#           edit_portfolio GET    /portfolios/:id/edit(.:format) portfolios#edit
#                portfolio PATCH  /portfolios/:id(.:format)      portfolios#update
#                          PUT    /portfolios/:id(.:format)      portfolios#update
#                          DELETE /portfolios/:id(.:format)      portfolios#destroy
#           show_portfolio GET    /portfolio/:id(.:format)       portfolios#show
#           portfolio_sort PUT    /portfolio/sort(.:format)      portfolios#sort
#           publicize_blog POST   /blogs/:id/publicize(.:format) blogs#publicize
#                    blogs GET    /blogs(.:format)               blogs#index
#                          POST   /blogs(.:format)               blogs#create
#                 new_blog GET    /blogs/new(.:format)           blogs#new
#                edit_blog GET    /blogs/:id/edit(.:format)      blogs#edit
#                     blog GET    /blogs/:id(.:format)           blogs#show
#                          PATCH  /blogs/:id(.:format)           blogs#update
#                          PUT    /blogs/:id(.:format)           blogs#update
#                          DELETE /blogs/:id(.:format)           blogs#destroy
#                     home GET    /home(.:format)                pages#home
#                    about GET    /about(.:format)               pages#about
#                  contact GET    /contact(.:format)             pages#contact
#                tech_news GET    /tech-news(.:format)           pages#tech_news
#                     root GET    /                              pages#home
#

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout',
                                             sign_up: 'register' }
  resources :portfolios, except: [:show]

  # Not needed since using websockets
  # resources :comments

  # adds show_portfolio_path
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'
  put 'portfolio/sort', to: 'portfolios#sort'

  # get 'topics', to: 'topics#index'
  # get 'topics/:id', to: 'topics#show'
  resources :topics, only: [:index, :show]

  resources :blogs do
    member do
      post :publicize
    end
  end

  mount ActionCable.server => '/cable'

  # controller/action mapping
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  root to: 'pages#home'
end

Resume/app/views/shared/_alerts.html.erb
<div class="circumspection">
  <% if flash[:alert] %>
    <%= js add_gritter(flash[:alert], title: 'Alert!'), image: :warning %>
  <% elsif flash[:notice] %>
    <%= js add_gritter(flash[:notice], title: 'Notice!', image: :notice) %>
  <% elsif flash[:error] %>
    <%= js add_gritter(flash[:error], title: 'Error!', image: :error) %>
  <% end %>
</div>

Resume/app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto app-footer">
  <div class="inner">
    <p><%= dynamic_copyright('Appsbyahrens', 'All Rights Reserved') %></p>
  </div>
</footer>

Resume/app/views/shared/_application_navigation.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Appsbyahrens</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= navigation_helper('nav-link', :span) %>
      <%= login_links_helper('application') %>
    </nav>
  </div>
</header>

Resume/app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= dynamic_copyright('Appsbyahrens', 'All Rights Reserved') %></p>
</footer>

Resume/app/views/shared/_blog_navigation.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 pt-1">
      <a class="text-muted" href="#">Subscribe</a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Appsbyahrens Blog</a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <a class="text-muted" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
      </a>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
</header>

<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= navigation_helper('p-2 text-muted', :span) %>
    <%= login_links_helper('blogs') %>
  </nav>
</div>

Resume/app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">A blog where I discuss the latest news in iOS development & Fortnite. Could even talk about other technologies such as Swift, Kotlin, and Ruby on Rails</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Topics</h4>
    <ol class="list-unstyled mb-0">
      <% topics.each do |topic| %>
        <li>
          <h5><%= link_to topic.title, topic_path(topic) %> | <span class="badge badge-secondary"><%= topic.blogs.count %></span></h5>
        </li>
      <% end %>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <%= content_tag :a, href: 'https://www.github.com', class: 'social-link' do %>
            <%= fa_icon 'github', class: "fa-2x" %>
          <% end %>
          <%= content_tag :a, href: 'https://www.instagram.com', class: 'social-link' do %>
            <%= fa_icon 'instagram', class: "fa-2x" %>
          <% end %>
        </div>
        <div class="col-sm-12">
          <%= content_tag :a, href: 'https://www.twitter.com', class: 'social-link' do %>
            <%= fa_icon 'twitter', class: "fa-2x" %>
          <% end %>
          <%= content_tag :a, href: 'https://www.facebook.com', class: 'social-link' do %>
            <%= fa_icon 'facebook-f', class: "fa-2x" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</aside>

Resume/app/views/shared/_navigation_bar.html.erb
<div class="<%= location %>">
  <div>
    <%= link_to 'Home', home_path %>
  </div>
  <div>
    <%= link_to 'About', about_path %>
  </div>
  <div>
    <%= link_to 'Contact', contact_path %>
  </div>
  <div>
    <%= link_to 'Blogs', blogs_path %>
  </div>
  <div>
    <%= link_to 'Portfolio', portfolios_path %>
  </div>
  <%= login_links_helper('blogs') %>
</div>

Resume/app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'Portfolios', portfolios_path %>
      |
      <a href="#">Back to top</a>
    </p>
    <p><%= dynamic_copyright('Appsbyahrens', 'All Rights Reserved') %></p>
  </div>
</footer>

Resume/app/views/shared/_portfolio_navigation.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white"><%= link_to 'About', about_path, class: 'text-white' %></h4>
          <p class="text-muted">
            Appsbyahrens has some interesting facts. We work on all types of project from mobile to web. Check them out.
            Also not opposed to playing some Fortnite. We won't play with any bush wookies.
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= navigation_helper('text-white', :li) %>
            <%= login_links_helper('portfolio') %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Appsbyahrens</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>