TimeTracker/config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                   Controller#Action
#    companies GET    /companies(.:format)          companies#index
#              POST   /companies(.:format)          companies#create
#  new_company GET    /companies/new(.:format)      companies#new
# edit_company GET    /companies/:id/edit(.:format) companies#edit
#      company GET    /companies/:id(.:format)      companies#show
#              PATCH  /companies/:id(.:format)      companies#update
#              PUT    /companies/:id(.:format)      companies#update
#              DELETE /companies/:id(.:format)      companies#destroy
#     projects GET    /projects(.:format)           projects#index
#              POST   /projects(.:format)           projects#create
#  new_project GET    /projects/new(.:format)       projects#new
# edit_project GET    /projects/:id/edit(.:format)  projects#edit
#      project GET    /projects/:id(.:format)       projects#show
#              PATCH  /projects/:id(.:format)       projects#update
#              PUT    /projects/:id(.:format)       projects#update
#              DELETE /projects/:id(.:format)       projects#destroy
#        works GET    /works(.:format)              works#index
#              POST   /works(.:format)              works#create
#     new_work GET    /works/new(.:format)          works#new
#    edit_work GET    /works/:id/edit(.:format)     works#edit
#         work GET    /works/:id(.:format)          works#show
#              PATCH  /works/:id(.:format)          works#update
#              PUT    /works/:id(.:format)          works#update
#              DELETE /works/:id(.:format)          works#destroy
#

Rails.application.routes.draw do
  devise_for :users
  root 'companies#index'
  get 'recentworks/:days', to: 'works#index'
  get 'venture/:slug', to: 'projects#show'
  resources :companies
  resources :projects
  resources :works
end

TimeTracker/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id             :integer          not null, primary key
#  date_performed :datetime
#  hours          :integer
#  project_id     :integer
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Work < ApplicationRecord
  extend CsvModule
  
  belongs_to :project
  belongs_to :user

  scope :overtime, -> { where('hours > 8') }
  # scope :recent, -> { where("date_performed > '#{Time.now - 4.days}'") }

  validates :project, :user, presence: true
  validates :date_performed, presence: true
  validate :date_performed_cant_be_in_future
  validates :hours, numericality: { only_integer: true, greater_than: 0, less_than: 9 }

  def self.recentdays(number_of_days_ago)
    since = Time.now - number_of_days_ago.to_i.days
    where('date_performed > ?', since)
  end

  def date_performed_cant_be_in_future
    if date_performed.present? && date_performed > Date.today
      errors.add(:date_performed, 'cant be in the future')
    end
  end
end

TimeTracker/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: %i[show edit update]
  before_action :authenticate_user!, except: :index
  
  def index
    recents = Work.recentdays(params[:days]).order(date_performed: :desc)
    all = Work.all.order(date_performed: :desc)
    @works = params[:days] ? recents : all

    respond_to do |format|
      format.html # defaults to show.html.erb
      format.json { render json: @works }
      format.csv { send_data @works.to_csv }
    end
  end

  def show
    respond_to do |format|
      format.html # defaults to show.html.erb
      format.json { render json: @work }
    end
  end

  def edit
  end

  def update
    set_document
    if @work.update(work_params)
      flash[:notice] = 'Work successfully updated'
      redirect_to @work
    else
      render :edit
    end
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(work_params)
    set_document
    if @work.save
      flash[:notice] = 'Work successfully created'
      redirect_to @work
    else
      render :new
    end
  end

  private

  def set_document
    unless params[:document].nil?
      file = params[:document]
      name = "#{@work.project_id}-#{@work.user_id}-#{file.original_filename}"
      @work.document = name
      File.open(Rails.root.join('public', 'documents', name), 'wb') do |f|
        f.write(file.read)
      end
    end
  end

  def work_params
    params[:work].permit(:project_id, :user_id, :hours, :date_performed, :document)
  end

  def set_work
    @work = Work.find(params[:id])
  end
end

TimeTracker/app/helpers/works_helper.rb
module WorksHelper
end

TimeTracker/app/views/works/_form.html.erb
<%= form_with model: work, local: true, multipart: true, class: 'pure-form pure-form-stacked' do |f| %>
  <fieldset>
    <% if work.persisted? %>
      <legend>Update Work</legend>
    <% else %>
      <legend>Create Work</legend>
    <% end %>
    <div class="pure-control-group">
      <%= f.label :project_id, 'Project' %>
      <!-- Map project_id to id from Project display name of Project -->
      <%= f.collection_select :project_id, Project.all, :id, :name, id: :company_project_id, prompt: true, class: 'pure-input-1-2' %>
    </div>
    <div class="pure-control-group">
      <%= f.label :user_id, 'User' %>
      <!-- Map user_id to id from User display full_name -->
      <%= f.collection_select :user_id, User.all, :id, :full_name, id: :company_user_id, prompt: true, class: 'pure-input-1-2' %>
    </div>
    <div class="pure-control-group">
      <%= f.label :hours %>
      <%= f.select :hours, [1,2,3,4,5,6,7,8], id: :work_hours, prompt: true, class: 'pure-input-1-2' %>
    </div>
    <div class="pure-control-group">
      <%= f.label :date_performed %>
      <%= f.date_select :date_performed, id: :company_date_performed, class: 'pure-input-1-2', placeholder: 'Date Worked' %>
    </div>
    <div class="pure-control-group">
      <%= label_tag :document, 'Memos (Optional)' %>
      <%= file_field_tag :document %>
    </div>
    <div class="pure-control-group">
      <% if work.persisted? %>
        <%= f.submit 'Update Work', class: 'pure-button pure-button-primary' %>
      <% else %>
        <%= f.submit 'Create Work', class: 'pure-button pure-button-primary' %>
      <% end %>
    </div>
  </fieldset>
<% end %>

TimeTracker/app/views/works/_sidebar.html.erb
<h3>Aside</h3>
<ul>
  <li>
    <%= link_to 'All Works', works_path %>
  </li>
  <li>
    <%= link_to 'New Work', new_work_path %>
  </li>
  <% if local_assigns.has_key? :work %>
    <li>
      <%= link_to 'Edit Work', edit_work_path(work) %>
    </li>
  <% end %>
</ul>

TimeTracker/app/views/works/_work-table-header.html.erb
<tr>
  <td>
    Work For
  </td>
  <td>
    At Company
  </td>
  <td>
    Performed By
  </td>
  <td>
    Completed On
  </td>
  <td>
    Time Spent
  </td>
  <td></td>
</tr>

TimeTracker/app/views/works/_work.html.erb
<tr>
  <td>
    <span><%= link_to "#{ work.project.name }", project_path(work.project) %></span>
  </td>
  <td>
    <%= link_to work.project.company, company_path(work.project.company) %>
  </td>
  <td>
    <span><%= work.user %></span>
  </td>
  <td>
    <span><%= work.date_performed.to_formatted_s(:long_ordinal) %></span>
  </td>
  <td>
    <span><%= pluralize(work.hours, 'hour') %>
    </span>
  </td>
  <td>
    <%= link_to 'View', work_path(work) %>
  </td>
</tr>

TimeTracker/app/views/works/edit.html.erb
<%= render 'shared/form-errors', model: @work %>
<%= render 'form', work: @work %>

<!-- provide content from application.html.erb -->
<% content_for :aside do %>
  <% render 'sidebar' %>
<% end %>

TimeTracker/app/views/works/index.html.erb
<div>
  <table>
    <thead>
      <%= render 'work-table-header' %>
    </thead>
    <tbody>
      <%= render @works %>
    </tbody>
  </table>

  <!-- provide content from application.html.erb -->
  <% content_for :aside do %>
    <% render 'sidebar' %><% end %>
  </div>

TimeTracker/app/views/works/new.html.erb
<%= render 'shared/form-errors', model: @work %>
<%= render 'form', work: @work %>

<!-- provide content from application.html.erb -->
<% content_for :aside do %>
  <% render 'sidebar' %>
<% end %>

TimeTracker/app/views/works/show.html.erb
<h1>Work for
  <%= @work.project.company.name %></h1>
<p>
  Project name:
  <%= @work.project.name %>
  performed by
  <%= @work.user.full_name %>
  total time spent
  <%= @work.hours %>
</p>
<p>
  <%= @work.inspect %>
</p>

<% if @work.document %>
  <p>
    Find document @ <%= link_to 'Uploaded File', "/documents/#{@work.document}", target: '_blank' %>
  </p>
<% end %>

<!-- provide content from application.html.erb -->
<% content_for :aside do %>
  <% render 'sidebar', work: @work  %>
<% end %>