Scheduler/config/routes.rb
# == Route Map
#
#                Prefix Verb   URI Pattern                           Controller#Action
#           admin_users GET    /admin/users(.:format)                admin/users#index
#                       POST   /admin/users(.:format)                admin/users#create
#        new_admin_user GET    /admin/users/new(.:format)            admin/users#new
#       edit_admin_user GET    /admin/users/:id/edit(.:format)       admin/users#edit
#            admin_user GET    /admin/users/:id(.:format)            admin/users#show
#                       PATCH  /admin/users/:id(.:format)            admin/users#update
#                       PUT    /admin/users/:id(.:format)            admin/users#update
#                       DELETE /admin/users/:id(.:format)            admin/users#destroy
#       admin_time_offs GET    /admin/time_offs(.:format)            admin/time_offs#index
#                       POST   /admin/time_offs(.:format)            admin/time_offs#create
#    new_admin_time_off GET    /admin/time_offs/new(.:format)        admin/time_offs#new
#   edit_admin_time_off GET    /admin/time_offs/:id/edit(.:format)   admin/time_offs#edit
#        admin_time_off GET    /admin/time_offs/:id(.:format)        admin/time_offs#show
#                       PATCH  /admin/time_offs/:id(.:format)        admin/time_offs#update
#                       PUT    /admin/time_offs/:id(.:format)        admin/time_offs#update
#                       DELETE /admin/time_offs/:id(.:format)        admin/time_offs#destroy
#     admin_admin_users GET    /admin/admin_users(.:format)          admin/admin_users#index
#                       POST   /admin/admin_users(.:format)          admin/admin_users#create
#  new_admin_admin_user GET    /admin/admin_users/new(.:format)      admin/admin_users#new
# edit_admin_admin_user GET    /admin/admin_users/:id/edit(.:format) admin/admin_users#edit
#      admin_admin_user GET    /admin/admin_users/:id(.:format)      admin/admin_users#show
#                       PATCH  /admin/admin_users/:id(.:format)      admin/admin_users#update
#                       PUT    /admin/admin_users/:id(.:format)      admin/admin_users#update
#                       DELETE /admin/admin_users/:id(.:format)      admin/admin_users#destroy
#            admin_root GET    /admin(.:format)                      admin/users#index
#            user_index GET    /user/index(.:format)                 user#index
#             time_offs GET    /time_offs(.:format)                  time_offs#index
#                       POST   /time_offs(.:format)                  time_offs#create
#          new_time_off GET    /time_offs/new(.:format)              time_offs#new
#         edit_time_off GET    /time_offs/:id/edit(.:format)         time_offs#edit
#              time_off GET    /time_offs/:id(.:format)              time_offs#show
#                       PATCH  /time_offs/:id(.:format)              time_offs#update
#                       PUT    /time_offs/:id(.:format)              time_offs#update
#                       DELETE /time_offs/:id(.:format)              time_offs#destroy
#      new_user_session GET    /users/sign_in(.:format)              devise/sessions#new
#          user_session POST   /users/sign_in(.:format)              devise/sessions#create
#  destroy_user_session DELETE /users/sign_out(.:format)             devise/sessions#destroy
#     new_user_password GET    /users/password/new(.:format)         devise/passwords#new
#    edit_user_password GET    /users/password/edit(.:format)        devise/passwords#edit
#         user_password PATCH  /users/password(.:format)             devise/passwords#update
#                       PUT    /users/password(.:format)             devise/passwords#update
#                       POST   /users/password(.:format)             devise/passwords#create
#       static_homepage GET    /static/homepage(.:format)            static#homepage
#                  root GET    /                                     static#homepage
#

Rails.application.routes.draw do
  resources :audit_logs, only: [:show, :index, :create, :update] do
    member do
      get :confirm
    end
  end
  mount Peek::Railtie => '/peek'

  namespace :admin do
    resources :users
    resources :employees
    resources :time_offs
    resources :admin_users
    root to: 'users#index'
  end

  get 'user/index'
  get 'static/homepage'
  resources :time_offs do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

Scheduler/app/views/partials/_navigation-bar.html.erb
<div class="logo">
  <h1>TimeTracker</h1>
</div>

<ul class="custom-navigation-bar nav nav-tabs">
  <li class="<%= navigation_active?(root_path) %>">
    <%= link_to '', root_path , class: 'glyphicon glyphicon-home'%>
  </li>
  <li class="<%= navigation_active?(time_offs_path) %>">
    <%= link_to 'All Requests', time_offs_path %>
  </li>
  <% if user_signed_in? && policy(AuditLog).index? %>
    <li class="<%= navigation_active?(audit_logs_path) %>">
      <%= link_to 'Audit Log', audit_logs_path %>
    </li>
  <% end %>
  <li class="<%= navigation_active?(new_time_off_path) %>">
    <%= link_to 'Submit Hours', new_time_off_path %>
  </li>
  <% if user_signed_in? && admin?(current_user) %>
    <li class="<%= navigation_active?(user_index_path) %>">
      <%= link_to 'Employees', user_index_path %>
    </li>
  <% end %>
  <li class="dropdown pull-right">
    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account<strong class="caret"></strong>
    </a>
    <ul class="dropdown-menu">
      <% if user_signed_in? %>
        <li class="dropdown-header">
          Hello
          <%= "#{current_user.first_name} #{current_user.last_name}" %>
        </li>
        <% if admin?(current_user) %>
          <li>
            <%= link_to 'Admin', admin_root_path %>
          </li>
        <% end %>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </li>
</ul>